### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by nxvvvv** [sanglantes/seb-qtbypass#1]
Frankly, how does this work since clipboard will be cleared again and again by the Clipboard service inside SafeExamBrowser, this doesn't seem too work. Also, you'll not be able to copy or paste inside the SEB. So, how does it work?

**Comment by sanglantes** [comment]
This being a public repository is a mistake to begin with. Now, to answer your question: It works like a charm (pre SEB 3.6.0). The way you're describing "Clipboard service" is not how SEB works. The code's all there. Take a gander.

**Comment by nxvvvv** [comment]
What happened post 3.6?

**Comment by sanglantes** [comment]
> Won't work for 3.6? And why?
https://github.com/SafeExamBrowser/seb-win-refactoring/issues/625

**Comment by nxvvvv** [comment]
I'll look upon that. I'll try to make a few modifications myself
